version: '3.8'
name: chatapp
services:
  mysql:
    image: mysql:8.4.0
    volumes:
      - ./config/mysql:/etc/mysql/conf.d
    #   - ~/volumes/jhipster/chatapp/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=chatapp
    ports:
      - '3306:3306' # Ha több gépről szeretnéd elérni
    command: mysqld --lower_case_table_names=1 --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    healthcheck:
      test: ['CMD', 'mysql', '-e', 'SHOW DATABASES;']
      interval: 5s
      timeout: 5s
      retries: 10
